### ISSUE TITLE
Use upstream YNATM

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/batch-submitter#63]
Since our PR to YNATM was [merged](https://github.com/kendricktan/ynatm/pull/8), can we replace the dependency with the upstream one and delete our YNATM repository?

**Comment by smartcontracts** [comment]
Agree. Sounds like this is a good first issue for someone.

**Comment by tynes** [comment]
I specifically made a fork to prevent supply chain attacks

**Comment by tynes** [comment]
I don't think the maintainer upstream is malicious but every dependency that is included in the batch-submitter should be scrutinized because of how important its hot key is

**Comment by smartcontracts** [comment]
Hmmmm okay let's consider this case carefully. Removing from good first issues list for now.

**Comment by gakonst** [comment]
Thanks for clarifying @tynes!
